### PR TITLE
Kul 216/minted flag in the prompt

### PR DESCRIPTION
**Pull request by yuliefas**
depende on https://github.com/CrewAI/CrewAI/pull/239

### CODE REVIEW

**Comment by empeje** [comment]
Ada perubahan di contract nya?

**Comment by empeje** [comment]
Ada type error pass build landing page FYI @yuliefas @AhlOct

**Comment by yuliefas** [comment]
> Ada perubahan di contract nya?

gak ada mas, cuma build nya aja dari remix, yang build @AhlOct

**Review by AhlOct — APPROVED** [review]

**Comment by yuliefas** [comment]
> Ada type error pass build landing page FYI @yuliefas @AhlOct

fixed mas

**Pull request merged**
